# Generated by Django 5.1.2 on 2024-10-31 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='Category',
            new_name='category',
        ),
    ]
